# Generated by Django 6.1.1 on 2026-09-25 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leetcode_username', models.CharField(blank=True, max_length=100)),
                ('leetcode_ranking', models.PositiveIntegerField(blank=True, null=True)),
                ('leetcode_solved_count', models.PositiveIntegerField(default=0)),
                ('leetcode_easy_count', models.PositiveIntegerField(default=0)),
                ('leetcode_medium_count', models.PositiveIntegerField(default=0)),
                ('leetcode_hard_count', models.PositiveIntegerField(default=0)),
                ('leetcode_last_synced', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
