# Generated by Django 6.1.1 on 2026-10-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='leetcode_avatar_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='leetcode_profile_url',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='leetcode_real_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='leetcode_topic_stats',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
