# Generated by Django 6.1.1 on 2026-09-25 09:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pattern', models.CharField(choices=[('TWO_POINTER', 'Two Pointer'), ('SLIDING_WINDOW', 'Sliding Window'), ('DP', 'Dynamic Programming'), ('BACKTRACKING', 'Backtracking'), ('GREEDY', 'Greedy'), ('GRAPH', 'Graph Traversal'), ('BINARY_SEARCH', 'Binary Search'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], max_length=10)),
                ('link', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_mastered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='tracker.topic')),
            ],
            options={
                'verbose_name': 'Problem',
                'verbose_name_plural': 'Problems',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_taken_minutes', models.PositiveIntegerField(help_text='Time taken in minutes')),
                ('was_successful', models.BooleanField(default=True)),
                ('approach_notes', models.TextField(blank=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='tracker.problem')),
            ],
            options={
                'verbose_name': 'Attempt',
                'verbose_name_plural': 'Attempts',
                'ordering': ['-solved_at'],
            },
        ),
        migrations.CreateModel(
            name='RevisionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ease_factor', models.FloatField(default=2.5)),
                ('interval_days', models.PositiveIntegerField(default=1)),
                ('repetitions', models.PositiveIntegerField(default=0)),
                ('next_review_date', models.DateField(default=django.utils.timezone.now)),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revision', to='tracker.problem')),
            ],
        ),
    ]
