# Generated by Django 6.1.1 on 2026-09-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_seed_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='pattern',
            field=models.CharField(choices=[('TWO_POINTER', 'Two Pointers'), ('FAST_SLOW', 'Fast & Slow Pointers'), ('SLIDING_WINDOW', 'Sliding Window'), ('INTERVALS', 'Merge Intervals'), ('MONOTONIC_STACK', 'Monotonic Stack / Queue'), ('DP', 'Dynamic Programming'), ('BACKTRACKING', 'Backtracking'), ('GREEDY', 'Greedy'), ('GRAPH', 'Graph Traversal (BFS/DFS)'), ('UNION_FIND', 'Union Find / Disjoint Set'), ('BINARY_SEARCH', 'Binary Search'), ('HEAP_TOP_K', "Top 'K' Elements (Heap)"), ('TREE_TRAVERSAL', 'Tree BFS / DFS'), ('TRIE', 'Trie / Prefix Tree'), ('BIT_MANIPULATION', 'Bit Manipulation'), ('OTHER', 'Other / General')], default='OTHER', max_length=30),
        ),
    ]
