# Generated by Django 6.1.1 on 2026-10-01 07:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_problem_pattern'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='supporting_concepts',
            field=models.CharField(blank=True, help_text='Supporting DSA concepts, e.g. HashMap, Two Pointers, Prefix Sum', max_length=255),
        ),
        migrations.CreateModel(
            name='CanonicalInterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('pattern', models.CharField(choices=[('TWO_POINTER', 'Two Pointers'), ('FAST_SLOW', 'Fast & Slow Pointers'), ('SLIDING_WINDOW', 'Sliding Window'), ('INTERVALS', 'Merge Intervals'), ('MONOTONIC_STACK', 'Monotonic Stack / Queue'), ('DP', 'Dynamic Programming'), ('BACKTRACKING', 'Backtracking'), ('GREEDY', 'Greedy'), ('GRAPH', 'Graph Traversal (BFS/DFS)'), ('UNION_FIND', 'Union Find / Disjoint Set'), ('BINARY_SEARCH', 'Binary Search'), ('HEAP_TOP_K', "Top 'K' Elements (Heap)"), ('TREE_TRAVERSAL', 'Tree BFS / DFS'), ('TRIE', 'Trie / Prefix Tree'), ('BIT_MANIPULATION', 'Bit Manipulation'), ('OTHER', 'Other / General')], default='OTHER', max_length=30)),
                ('supporting_concepts', models.CharField(blank=True, max_length=255)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], max_length=10)),
                ('target_tracks', models.CharField(default='GENERAL,BACKEND,PRODUCT', help_text='Comma-separated tracks: GENERAL, FRONTEND, BACKEND, PRODUCT', max_length=200)),
                ('company_tags', models.CharField(blank=True, help_text='e.g. Google, Meta, Amazon', max_length=200)),
                ('description', models.TextField()),
                ('examples', models.TextField(blank=True)),
                ('constraints', models.TextField(blank=True)),
                ('hints', models.JSONField(default=list, help_text='List of tiered hints (1: Intuition, 2: DS, 3: Approach)')),
                ('follow_ups', models.JSONField(default=list, help_text='List of interviewer follow-ups with answers')),
                ('optimal_time_complexity', models.CharField(blank=True, max_length=50)),
                ('optimal_space_complexity', models.CharField(blank=True, max_length=50)),
                ('leetcode_url', models.URLField(blank=True)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canonical_questions', to='tracker.topic')),
            ],
            options={
                'verbose_name': 'Canonical Interview Question',
                'verbose_name_plural': 'Canonical Interview Questions',
                'ordering': ['difficulty', 'title'],
            },
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(default='GENERAL', max_length=50)),
                ('difficulty', models.CharField(default='MEDIUM', max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(default=45)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('score', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interview Session',
                'verbose_name_plural': 'Interview Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField(default=0.0)),
                ('problem_solving_score', models.FloatField(default=0.0)),
                ('pattern_recognition_score', models.FloatField(default=0.0)),
                ('time_management_score', models.FloatField(default=0.0)),
                ('optimization_score', models.FloatField(default=0.0)),
                ('consistency_score', models.FloatField(default=0.0)),
                ('weak_area', models.CharField(blank=True, max_length=150)),
                ('recommended_patterns', models.JSONField(default=list)),
                ('revision_roadmap', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='tracker.interviewsession')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewQuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_order', models.PositiveIntegerField(default=1)),
                ('time_taken_seconds', models.PositiveIntegerField(default=0)),
                ('hints_revealed', models.PositiveIntegerField(default=0)),
                ('candidate_code', models.TextField(blank=True)),
                ('candidate_approach', models.TextField(blank=True)),
                ('follow_up_answer', models.TextField(blank=True)),
                ('was_passed', models.BooleanField(default=False)),
                ('feedback_notes', models.TextField(blank=True)),
                ('canonical_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.canonicalinterviewquestion')),
                ('user_problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.problem')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tracker.interviewsession')),
            ],
            options={
                'ordering': ['question_order'],
            },
        ),
    ]
